# Generated by Django 3.0.3 on 2020-03-05 18:08

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('city_hall', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Region',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('code', models.CharField(max_length=11)),
                ('name', models.CharField(max_length=200)),
                ('city_halls', models.ManyToManyField(blank=True, related_name='regions', to='city_hall.CityHall')),
            ],
        ),
    ]
